### ISSUE TITLE
Api key selalu invalid

### ISSUE THREAD

**Issue by xfkrahmad** [Dipantry/rajaongkir#6]
![Screenshot_75](https://user-images.githubusercontent.com/71373710/197388897-e36b746d-b760-4642-b91d-e597e24b28fd.png)
![Screenshot_76](https://user-images.githubusercontent.com/71373710/197388943-88bd8f2b-c45b-465a-999e-07efea7b447c.png)

Api key selalu invalid, atau ada kesalahan sewaktu menginstall?

Laravel 9

**Comment by Rigsto** [comment]
Ketika command dipanggil, sistem akan melakukan pengecekan ke server raja ongkir apakah API Key dan Package valid dengan cara memanggil API Province.

Disarankan untuk melakukan pengecekan pada API Key dan Package. 
Atau bisa juga mencoba testing secara langsung ke endpoint rajaongkir.
