### ISSUE TITLE
Seeder Tidak Bekerja Sempurna

### ISSUE THREAD

**Issue by aziz-prasetyo** [Dipantry/rajaongkir#7]
Setelah melakukan `php artisan rajaongkir:seed`, data pada tabel `countries` dan `subdistricts` tidak terisi oleh **seeder**. Sedangkan data pada tabel `cities` dan `provinces` terisi dengan baik.

**Comment by Rigsto** [comment]
Kalau boleh tahu, menggunakan Laravel atau Native? Bisa minta versinya juga? Ini menggunakan rajaongkir package apa ya?

**Comment by aziz-prasetyo** [comment]
Oh iya mas, mohon maaf. Ternyata untuk bisa mendapatkan semua data yang disediakan oleh `RajaOngkir` harus menggunakan package `Pro`. Jadi, wajar kalau package yang saya pakai (`Starter`) tidak bisa mendapatkan data pada table `countries` dan `subdistricts` ketika melakukan perintah `php artisan rajaongkir:seed`.
